# SM64 Randomizer Generator Constants File
# Game Versions: All Regions, Vanilla SM64
# Author: Andre Meyer

# This file contains constant variables and sensible names, so they can be referenced
# in the configuration.

collision_types:
  ENV_DEFAULT: 0x00
  BURN_FROST: 0x01
  CLIMBABLE_CEILING: 0x05
  SLOWDOWN_MARIO: 0x09 # Sand, Snow, etc
  DEATH_FLOOR: 0x0A
  CLOSE_CAMERA: 0x0B # Zooms in Camera
  WATER: 0x0D
  WATER_FLOWING: 0x0E
  INTANGIBLE: 0x12
  SLIPPERY: 0x13
  SLIPPERY_SLIGHTLY: 0x14
  ANTI_SLIPPERY: 0x15
  NOISY_TERRAIN: 0x1A
  INSTANT_WARP_A: 0x1B
  INSTANT_WARP_B: 0x1C
  INSTANT_WARP_C: 0x1D
  INSTANT_WARP_D: 0x1E
  SAND: 0x21 # Depth of 10 units
  QUICKSAND_LETAHL_SLOW: 0x22
  QUICKSAND_LETHAL_INSTANT: 0x23
  QUICKSAND_FLOW_160: 0x24
  QUICKSAND_FLOW_25: 0x25
  QUICKSAND_MOVING_60: 0x26
  QUICKSAND_FLOWING_60: 0x27
  QUICKSAND_FLOW_LETHAL: 0x2D
  WALL_FENCE_CANON: 0x28
  DEFAULT_NOISE: 0x29
  SLIPPERY_NOISE: 0x2A
  WIND: 0x2C
  SLIPPERY_ICE: 0x2E # CCM
  WINGCAP_WARP: 0x2F
  HARD_FLOOR: 0x30
  SURFACE_WARP: 0x32
  TIMER_START: 0x33 # PSS
  TIMER_END: 0x34 # PSS
  SLIPPERY_HARD: 0x35
  SLIPPERY_HARD_CCM: 0x36 # CCM
  ANTI_ICE: 0x37 # Non Slippery in Ice Levels
  DEATHFLOOR_FIND: 0x38
  WIDE_CAMERA: 0x65 # BOB Boss
  WALLS_THI_3: 0x66 # THI Walls
  PYRAMID_TOP_TRIGGER: 0x6E # SSL
  CAMERA_BOWSER_1: 0x6F
  CAMERA_BOB: 0x70
  CAMERA_RESTRICT: 0x72
  SLIDE_UNUSED_NOISE_A: 0x73
  SLIDE_UNUSED_NOISE_B: 0x74
  CAMERA_CCM: 0x75
  SURFACE_FLAGS: 0x76
  SURFACE_FLAGS_UNUSED: 0x77
  DORRIE_SWITCH: 0x7A
  VANISH_CAP_WALL: 0x7B
  POOL_WARP: 0xFD
  BOWSER_1_TRAPDOOR: 0xFF


